<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>WebsocketPlugin</AssemblyName>
    <RootNamespace>Logitech.LogiActions.WebsocketPlugin</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Actions\**\*.cs" />
    <Compile Include="Helpers\**\*.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="WebsocketApplication.cs" />
    <Compile Include="WebsocketPlugin.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="metadata\LoupedeckPackage.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PluginSdk">
      <HintPath Condition="Exists('$(USERPROFILE)\\AppData\\Local\\Logi\\LogiPluginService\\Sdk\\PluginSdk.dll')">$(USERPROFILE)\AppData\Local\Logi\LogiPluginService\Sdk\PluginSdk.dll</HintPath>
      <HintPath Condition="Exists('$(HOME)/Library/Application Support/Logi/LogiPluginService/Sdk/PluginSdk.dll')">$(HOME)/Library/Application Support/Logi/LogiPluginService/Sdk/PluginSdk.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Net.WebSockets.Client" Version="8.0.0" />
  </ItemGroup>
</Project>
